// <auto-generated />
using LawEnforcement.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LawEnforcement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210705120517_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LawEnforcement.API.Models.CrimeEvent", b =>
                {
                    b.Property<string>("CrimeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LawEnforcementId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingPersonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfEvent")
                        .HasColumnType("int");

                    b.HasKey("CrimeId");

                    b.ToTable("CrimeEvents");
                });

            modelBuilder.Entity("LawEnforcement.API.Models.Dto.CrimeEventDto", b =>
                {
                    b.Property<string>("CrimeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LawEnfId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LawEnforcementId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingPersonEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfEvent")
                        .HasColumnType("int");

                    b.HasKey("CrimeId");

                    b.HasIndex("LawEnfId");

                    b.ToTable("CrimeEventDto");
                });

            modelBuilder.Entity("LawEnforcement.API.Models.LawEnf", b =>
                {
                    b.Property<string>("LawEnfId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RankOfLawEnforcement")
                        .HasColumnType("int");

                    b.HasKey("LawEnfId");

                    b.ToTable("LawEnfs");

                    b.HasData(
                        new
                        {
                            LawEnfId = "1",
                            RankOfLawEnforcement = 0
                        },
                        new
                        {
                            LawEnfId = "2",
                            RankOfLawEnforcement = 2
                        },
                        new
                        {
                            LawEnfId = "3",
                            RankOfLawEnforcement = 1
                        });
                });

            modelBuilder.Entity("LawEnforcement.API.Models.Dto.CrimeEventDto", b =>
                {
                    b.HasOne("LawEnforcement.API.Models.LawEnf", null)
                        .WithMany("CrimeEvents")
                        .HasForeignKey("LawEnfId");
                });

            modelBuilder.Entity("LawEnforcement.API.Models.LawEnf", b =>
                {
                    b.Navigation("CrimeEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
